### ISSUE TITLE
Nice view on iPad, but how to positioning it on the view?

### ISSUE THREAD

**Issue by caspahouzer** [obscure-com/TiActionSheetPicker#2]

**Comment by pegli** [comment]
You can now specify the origin of the popover on iPad by passing an object argument to the `show()` method containing a property named `origin` that points to a valid view.  See the updated README.md for an example.

**Comment by caspahouzer** [comment]
awesome. thank you!

Am 11.04.2013 um 19:50 schrieb Paul Mietz Egli notifications@github.com:

**Comment by caspahouzer** [comment]
ok, just tested it. unfortunetaly it won't work with your example. i took the code from the app.js.
![iOS Simulator Bildschirmfoto 11 04 2013 20 29 11](https://f.cloud.github.com/assets/1126641/369357/e1f54de2-a2d5-11e2-818c-066d0c5e82f1.png)

**Comment by pegli** [comment]
Did you delete your build directory after you updated the module?

**Comment by caspahouzer** [comment]
Yes, i did
- Sebastian 

Sent from my iPhone

Am 11.04.2013 um 20:31 schrieb Paul Mietz Egli notifications@github.com:

**Comment by pegli** [comment]
Hm.  Can you try running `git submodule sync` and `git submodule update` in the module's source directory, cleaning and rebuilding?

**Comment by caspahouzer** [comment]
that did the trick. thanks.
may I open one other issue please? then I'm very very happy with this module ;)

Am 11.04.2013 um 20:56 schrieb Paul Mietz Egli notifications@github.com:
