### ISSUE TITLE
Eventlistener for "Done" button

### ISSUE THREAD

**Issue by caspahouzer** [obscure-com/TiActionSheetPicker#3]
There is an event for the cancel button click. Does this exists also for the done button with the chosen row in result?

**Comment by pegli** [comment]
Both the string picker and the date picker fire a "change" event when the Done button is pressed.  For string pickers, the object that is passed to the event contains a `selectedIndex` property which indicates which row was selected when the button was pressed.  The date picker contains a `selectedDate` property with a Date object.  The `example/app.js` shows event handlers for both types of pickers.

Let me know if I'm not understanding your question correctly!

**Comment by caspahouzer** [comment]
Yes, you do. And it does what I want. Another question: The result only contains selectedIndex? There's no int index? Or can I give an normal row object as array to the picker?

Am 11.04.2013 um 21:10 schrieb Paul Mietz Egli notifications@github.com:

**Comment by pegli** [comment]
I'm not sure I understand the difference between selectedIndex and int index.  Can you explain a little bit more about what you want the select event to provide?

Right now you cannot provide an array of Ti.UI.PickerRow objects to the picker.  I would have to make significant changes to the underlying library to allow row objects instead of plain strings.

**Comment by caspahouzer** [comment]
Let's take your example:

var rows = ['aardvark', 'bandicoot', 'cougar', 'dugong', 'emu', 'finch', ....];

selectedIndex is now 'bandicoot' e.g.
but the index would be 1. at cougar it would be 2 etc

I can't work with the title really good, because this ends in string comparisons. the index of the row would be enough. there is no absolute need for pickerrowitems. but a counted index would be great.

Am 11.04.2013 um 22:17 schrieb Paul Mietz Egli notifications@github.com:

**Comment by pegli** [comment]
The selectedIndex property is an integer, zero-based index, not a string.  Take a look at the sample code:

``` javascript
stringPicker.addEventListener('change', function(e) {
  label.text = rows[e.selectedIndex];
});
```

In this event handler, `e.selectedIndex` is an integer.  Try replacing the line with:

``` javascript
    label.text = e.selectedIndex;
```

and the label would read 0 for aardvark, 1 for bandicoot, 2 for cougar, and so on.  Are you seeing different behavior than what I am describing?

**Comment by caspahouzer** [comment]
ah, ok... must have overread it. that's it.

thanks for your patience.

I will use it in my app: http://itunes.apple.com/us/app/fantastic-library/id425218953

again thanks for your work. the ipad view is absolutely nice!

Am 11.04.2013 um 22:40 schrieb Paul Mietz Egli notifications@github.com:
