### ISSUE TITLE
Exception error on device

### ISSUE THREAD

**Issue by caspahouzer** [obscure-com/TiActionSheetPicker#5]
I got an exception on the iphone 5. On simulator it works well.
Hope, you can help. Here is the expection:

Apr 23 14:37:49 Sebastians-iPhone AppName[8608] <Error>: -[NSNull isEqualToString:]: unrecognized selector sent to instance 0x39a9f080
Apr 23 14:37:49 Sebastians-iPhone AppName[8608] <Warning>: [ERROR] The application has crashed with an uncaught exception 'NSInvalidArgumentException'.
    Reason:
    -[NSNull isEqualToString:]: unrecognized selector sent to instance 0x39a9f080
    Stack trace:

```
0   CoreFoundation                      0x317353e7 <redacted> + 162
1   libobjc.A.dylib                     0x39430963 objc_exception_throw + 30
2   CoreFoundation                      0x31738f31 <redacted> + 0
3   CoreFoundation                      0x3173764d <redacted> + 392
4   CoreFoundation                      0x3168f208 _CF_forwarding_prep_0 + 24
5   UIKit                               0x33548455 <redacted> + 96
6   UIKit                               0x336fa743 <redacted> + 1050
7   UIKit                               0x3358f569 <redacted> + 408
8   UIKit                               0x33574391 <redacted> + 1316
9   UIKit                               0x3358b827 <redacted> + 206
10  UIKit                               0x335478c7 <redacted> + 258
11  QuartzCore                          0x332f3513 <redacted> + 214
12  QuartzCore                          0x332f30b5 <redacted> + 460
13  QuartzCore                          0x332f3fd9 <redacted> + 16
14  QuartzCore                          0x332f39c3 <redacted> + 238
15  QuartzCore                          0x332f37d5 <redacted> + 316
16  QuartzCore                          0x332f3639 <redacted> + 60
17  CoreFoundation                      0x3170a941 <redacted> + 20
18  CoreFoundation                      0x31708c39 <redacted> + 276
19  CoreFoundation                      0x31708f93 <redacted> + 746
20  CoreFoundation                      0x3167c23d CFRunLoopRunSpecific + 356
21  CoreFoundation                      0x3167c0c9 CFRunLoopRunInMode + 104
22  GraphicsServices                    0x3525b33b GSEventRunModal + 74
23  UIKit                               0x335982b9 UIApplicationMain + 1120
```

**Comment by caspahouzer** [comment]
Forget it. Error in my JS. Sorry

**Comment by caspahouzer** [comment]
Sorry, but it wasn't my fault. I just thought. If you might have a look at it. Would be nice.

**Comment by pegli** [comment]
Can you provide a sample app.js that reproduces the problem?

**Comment by caspahouzer** [comment]
hm... can't reproduce it in a single app.js

will refactor my code.
could be closed.
- Sebastian

Am 24.04.2013 um 17:19 schrieb Paul Mietz Egli notifications@github.com:

**Comment by pegli** [comment]
The stack trace above doesn't show where in the module the error occurred, so without some way to reproduce the error, I can't tell what might be going wrong.  I'd like to keep this issue open, however, in case we can come up with a way to reproduce the bug.

**Comment by caspahouzer** [comment]
thanks
- Sebastian

Am 24.04.2013 um 18:14 schrieb Paul Mietz Egli notifications@github.com:
