### ISSUE TITLE
Cancel button doesn't wokr

### ISSUE THREAD

**Issue by jamesdlow** [obscure-com/TiActionSheetPicker#8]
The cancel button doesn't work. It can be made to work with the following changes. I have initiated a pull request #7 https://github.com/pegli/TiActionSheetPicker/pull/7

Change this at lines 58-59

```
    // self.actionSheetPicker.hideCancel = YES;
    self.actionSheetPicker.hideCancel = [[self valueForKey:kHideCancelKey] boolValue];
```

Add this to line 100

```
- (void)actionPickerCancelled:(id)sender {
    [self forgetSelf];
    [self release];
}
```

**Comment by pegli** [comment]
Merged pull request #7.  Thanks again!
